apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: marsalsoren/tute-dude-backend:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: flask
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30001
