version: "3.9"

services:
  backend:
    build: ./backend
    hostname: todo-backend
    container_name: todo-backend
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - todo-network

  frontend:
    build: ./frontend
    container_name: todo-frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://todo-backend:8000
    depends_on:
      - backend
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
