version: "3.8"

services:
  backend:
    build: ./backend
    container_name: todo-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - todo-network

  frontend:
    build: ./frontend
    container_name: todo-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
